SensoStat.WebApplication/Controllers/HomeController.cs
namespace SensoStat.WebApplication.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            this.HttpContext.Request.Cookies = null;
            var test = this.HttpContext.Request.Cookies;
            this.HttpContext.Session.Clear();

            this.Response.Cookies.Delete("Jwt");
            this.Response.Cookies.Delete("Role");
            this.Response.Cookies.Delete("IdUser");

            return this.View();
        }

        public IActionResult Error()
        {
            return this.View("404");
        }
    }
}

SensoStat.WebApplication/Controllers/SessionController.cs
namespace SensoStat.WebApplication.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using SensoStat.Entities;
    using SensoStat.WebApplication.Services;
    using SensoStat.WebApplication.Services.Contracts;
    using SensoStat.WebApplication.ViewModels;

    public class SessionController : Controller
    {
        private readonly ISessionService _sessionService;

        public SessionController(ISessionService service)
        {
            this._sessionService = service;
        }

        public IActionResult Index()
        {
            var model = this._sessionService.GetSessions().ToList();
            return this.View(model);
        }

        [HttpGet]
        public IActionResult Archive()
        {
            var model = this._sessionService.GetSessionsClose().ToList();
            return this.View(model);
        }

        [HttpPost]
        public IActionResult Archive(int id)
        {
            this._sessionService.ArchiveSession(id);
            return this.RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(SessionViewModel session)
        {
            // IdPerson à remplacer
            session.IdPerson = Convert.ToInt32(this.Request.Cookies["IdUser"]);
            session.Etat = "Non-publiée";
            session.DateCreate = DateTime.Now;

            session = this._sessionService.MessagesToInstructions(session);

            this._sessionService.CreateSession(session);
            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this._sessionService.GetSessionById(id);
            model.Presentations = this._sessionService.GetPresentations(id);
            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(SessionViewModel session)
        {
            session = this._sessionService.MessagesToInstructions(session);

            session = this._sessionService.UpdateSession(session);
            session.Presentations = this._sessionService.GetPresentations(session.Id);

            return this.View(session);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (this._sessionService.DeleteSession(id))
            {
                return this.RedirectToAction("Index");
            }

            return this.RedirectToAction("edit", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> LoadFile(int id, IFormFile file)
        {
            var fileSave = this._sessionService.LoadFile(file, id);
            if (fileSave)
            {
                return this.RedirectToAction("edit", new { id = id });
            }

            this.ModelState.AddModelError(string.Empty, "Un problème est survenue, le fichier n'a pas été enregistré, veuillez réessayer.");
            return this.RedirectToAction("edit", new { id = id });
        }

        [HttpPost]
        public IActionResult Clone(int id)
        {
            var session = this._sessionService.CloneSession(id);

            return this.RedirectToAction("Index");
        }

        [HttpPost("{id}")]
        public IActionResult Publish(int id)
        {
            if (this._sessionService.Publish(id))
            {
                this.TempData["success"] = "La séance a bien été publiée.";
                return this.RedirectToAction("edit", new { id = id });
            }

            // ajouter message d'erreur de publication
            this.ModelState.AddModelError(string.Empty, "Un problème est survenue, le publication n'a pu être enregistrer, veuillez réessayer.");
            return this.RedirectToAction("edit", new { id = id });
        }

        public IActionResult Export(int id)
        {
            Stream? stream = this._sessionService.Export(id);

            var filename = this.Request.Form["filename"];

            return this.File(stream, "application/octet-stream", filename);
        }
        public IActionResult ExportSessionReponse(int id)
        {
            Stream? stream = this._sessionService.ExportSessionResponse(id);

            var filename = this.Request.Form["filename"];

            return this.File(stream, "application/octet-stream", filename);
        }
    }
}

SensoStat.WebApplication/Controllers/UserController.cs
namespace SensoStat.WebApplication.Controllers
{
    using System;
    using System.Security.Claims;
    using Microsoft.AspNetCore.Mvc;
    using SensoStat.WebApplication.Services.Contracts;
    using SensoStat.WebApplication.ViewModels;

    public class UserController : Controller
    {
        private UserViewModel model;

        private readonly IUserService _userService;

        private static List<RoleViewModel> listRoles;

        public UserController(IUserService userService)
        {
            this.model = new UserViewModel();
            this._userService = userService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Authenticate()
        {

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Authenticate(AuthentificationViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userAuthentified = this._userService.Authenticate(model);

                if (userAuthentified.Token == null)
                {
                    this.ModelState.AddModelError(string.Empty, "Utilisateur ou mot de passe incorrect.");
                    return this.View(model);
                }

                var claims = new ClaimsIdentity();
                var claimType = "Jwt";
                claims.AddClaim(new Claim(claimType, userAuthentified.Token));
                this.HttpContext.User.AddIdentity(claims);

                this.Response.Cookies.Append("Jwt", userAuthentified.Token, new CookieOptions { Expires = DateTime.Now.AddHours(1) });
                this.Response.Cookies.Append("Role", userAuthentified.RoleLibelle);
                this.Response.Cookies.Append("IdUser", userAuthentified.Id.ToString());

                return this.RedirectToAction(nameof(Index), "session");
            }
            return this.View(model);
        }

        public IActionResult Create()
        {
            listRoles = this._userService.GetRoles().ToList();
            this.model.Roles = listRoles;
            return this.View(this.model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("create")]
        public IActionResult Create(UserViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var user = this._userService.CreateUser(model);
                if (user.Id != 0)
                {
                    return this.RedirectToAction(nameof(Index), "session");
                }

                user.Roles = listRoles;
                this.ModelState.AddModelError(string.Empty, "Cet email est déjà utilisé pour un autre compte.");
                return this.View(user);
            }

            model.Roles = listRoles;
            return this.View(model);
        }
    }
}

SensoStat.WebApplication/Views/Home/Error404.cshtml
<div class="d-flex justify-content-center">
    <pre style="line-height: 1.25; white-space: pre;">
            \          Désolé           /
             \                         /
              \      Cette page       /
               ]    n'existe pas.    [    ,'|
               ]                     [   /  |
               ]___               ___[ ,'   |
               ]  ]\             /[  [ |:   |
               ]  ] \           / [  [ |:   |
               ]  ]  ]         [  [  [ |:   |
               ]  ]  ]__     __[  [  [ |:   |
               ]  ]  ] ]\ _ /[ [  [  [ |:   |
               ]  ]  ] ] (#) [ [  [  [ :===='
               ]  ]  ]_].nHn.[_[  [  [
               ]  ]  ]  HHHHH. [  [  [
               ]  ] /   `HH("N  \ [  [
               ]__]/     HHH  "  \[__[
               ]         NNN         [
               ]         N/"         [
               ]         N H         [
              /          N            \
             /           q,            \
            /                           \
    </pre>
</div>

SensoStat.WebApplication/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model SensoStat.WebApplication.ViewModels.AuthentificationViewModel
}

<div class="p-5">
    <div class="row">
        <form class="col-6 offset-3" method="post" asp-controller="user" asp-action="authenticate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="@Model.Email" class="form-label">Identifiant</label>
                <input asp-for="@Model.Email" name="model.Email" aria-describedby="userAuth" type="text" class="form-control rounded" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Password" class="form-label">Mot de passe</label>
                <input asp-for="@Model.Password" name="model.Password" aria-describedby="userCreate" type="password" class="form-control rounded" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-warning">Se connecter</button>
        </form>
    </div>

</div>

@section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

SensoStat.WebApplication/Views/Session/Archive.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model List<SensoStat.WebApplication.ViewModels.SessionViewModel>
}

<div class="p-5">
    <h2>Liste des séances archivées</h2>
    <hr />
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="table-secondary">
                <th scope="col">Nom de la séance</th>
                <th class="text-center" scope="col">Date de dernière modification</th>
                <th class="text-center" scope="col">Statut</th>
                <th class="text-center" scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var session in @Model)
            {
                <tr>
                    <td>@session.Name</td>
                    <td class="text-center">@session.DateUpdate.ToString("dd/MM/yyyy à HH:mm")</td>
                    <td class="text-center">@session.Etat</td>
                    <td class="d-flex justify-content-center">
                        <form method="post" asp-controller="session" asp-action="delete" asp-route-id="@session.Id">
                            <a class="ms-1 me-1" asp-controller="Session" asp-action="ExportData" asp-route-id="@session.Id"><i class="fas fa-download me-1"></i></a>
                        </form>
                        <form method="post" asp-controller="Session" asp-action="Clone" asp-route-id="@session.Id"> 
                            <button class="ms-1 me-1 btn btn-outline-primary bg-transparent btn-sm border-0" type="submit"><i class="far fa-clone"></i></button>
                        </form>
                        <form method="post" asp-controller="session" asp-action="delete" asp-route-id="@session.Id">
                            <button class="ms-2 me-1 btn btn-outline-primary btn-sm" type="submit"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<!-- Modal Validation suppression séance-->
<div class="modal fade" id="SuppSeance" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Supprimer la séance</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Êtes vous sûr de vouloir supprimer cette séance?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                <form method="post" asp-controller="session" asp-action="delete" asp-route-id="">
                    <button type="submit" class="btn btn-primary">Valider</button>
                </form>
            </div>
        </div>
    </div>
</div>

SensoStat.WebApplication/Views/Session/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	@model SensoStat.WebApplication.ViewModels.SessionViewModel
}
<div class="p-3">
	<h2>Créer une nouvelle séance</h2>
	<hr />

	<section class="row">
		<!-- div de gestion de la séance -->
		<div class="col-10">
            <form id="formSession" method="post" asp-controller="Session" asp-action="Create">
                <input type="hidden" asp-for="IdPerson" value="@Convert.ToInt32(this.Url.ActionContext.HttpContext.Request.Cookies["IdUser"])">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <!-- section du nom de la séance ainsi que sont status -->
                <span class="mb-4 d-flex justify-content-between">
                    <div class="d-flex">
                        <label for="exampleInputEmail1" class="form-label h5 me-1 mt-2">Nom de la séance :</label>
                        <span class="">
                            <input asp-for="Name" type="text" class="form-control" placeholder="Nom Séance">
                        </span>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </span>
                <p>Ajoutez vos instruction(s) / question(s) dans l'ordre chronologique du déroulé de la séance</p>
                <!-- section du message d'accueil -->
                <span class="mb-3 row">
                    <div class="col col-lg-2">
                        <label>Message d'accueil</label>
                    </div>
                    <div class="col-10">
                        <textarea asp-for="MsgAccueil" class="form-control" rows="1" oninput="auto_grow(this)" placeholder="ici doit être inscrit le message de début de séance !"></textarea>
                        <span asp-validation-for="MsgAccueil" class="text-danger"></span>
                    </div>
                </span>
                <!-- section qui ajoute des intruction / question -->
                <span id="SpanInstru">

                </span>
                <span asp-validation-for="Messages" class="text-danger"></span>

                <!-- section du message de fin -->
                <span class="mb-3 row">
                    <div class="col col-lg-2">
                        <label>Message de fin</label>
                    </div>
                    <div class="col-10">
                        <textarea asp-for="MsgFinal" class="form-control" rows="1" oninput="auto_grow(this)" placeholder="ici doit être inscrit le message de fin de séance !"></textarea>
                        <span asp-validation-for="MsgFinal" class="text-danger"></span>
                    </div>
                </span>
                <!-- button d'ajout d'instruction / question -->
            </form>
				<button class="btn btn-warning" onclick="addInstruction('Instruction')">Ajouter une instruction</button>
				<button class="btn btn-warning" onclick="addInstruction('Question')">Ajouter une question</button>
			
		</div>
		<!-- div contenant les button pour les fonctionnalité -->
		<div class="col-2 d-flex flex-column">
			<button class="btn btn-warning mb-2" form="formSession" type="submit">Enregistrer</button>
			<button class="btn btn-warning mb-2" type="button" data-bs-toggle="modal" data-bs-target="#AnnulerSeance">Annuler</button>
            <p>liste des tags : </p>

            <ul>
                <li>#codeProduit = pour ajouter le numéro du produit </li>
            </ul>
		</div>
	</section>
</div>

<!-- Modal Validation annulation séance-->
<div class="modal fade" id="AnnulerSeance" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Annuler la séance</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Êtes vous sûr de vouloir annuler cette séance?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
        <a type="button" class="btn btn-primary" asp-controller="session" asp-action="index">Valider</a>
      </div>
    </div>
  </div>
</div>

SensoStat.WebApplication/Views/Session/Delete.cshtml
<div class="p-3">
	<h2>Supprimer une séance</h2>
	<hr />
</div>

SensoStat.WebApplication/Views/Session/Index.cshtml
@model List<SensoStat.WebApplication.ViewModels.SessionViewModel>

<section class="p-5">
    <div class="row">
        <span class="col">
            <h2>Liste des séances actives</h2>
        </span>
        <span class="col text-end">
             <a class="btn btn-warning" asp-controller="session" asp-action="create">Nouvelle séance</a>
        </span>
    </div>
	<hr />
	<table class="table table-bordered table-striped table-hover">
      <thead>
        <tr class="table-secondary">
          <th scope="col">Nom de la séance</th>
          <th class="text-center" scope="col">Date de dernière modification</th>
          <th class="text-center" scope="col">Statut</th>
          <th class="text-center" scope="col">% de réponse</th>
          <th class="text-center" scope="col">% de complétion</th>
          <th class="text-center" scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>

          @foreach (var session in @Model)
          {
            <tr>
                <td>@session.Name</td>
                <td class="text-center">@session.DateUpdate.ToString("dd/MM/yyyy à HH:mm")</td>
                <td class="text-center">@session.Etat</td>
                <td class="text-end">%</td>
                <td class="text-end">%</td>
                <td class="d-flex justify-content-center">
                    <a class="ms-1 me-1" asp-controller="Session" asp-action="Edit" asp-route-id="@session.Id"><i class="fas fa-edit"></i></a>
                    <a class="ms-1 me-1" asp-controller="Session" asp-action="ExportData" asp-route-id="@session.Id"><i class="fas fa-download me-1"></i></a>
                    <form method="post" asp-controller="Session" asp-action="Clone" asp-route-id="@session.Id"> 
                        <button class="ms-1 me-1 btn btn-outline-primary bg-transparent btn-sm border-0" type="submit"><i class="far fa-clone"></i></button>
                    </form>
                    <form method="post" asp-controller="session" asp-action="archive" asp-route-id="@session.Id">
                        <button class="ms-1 me-1 btn btn-outline-primary btn-sm" type="submit"><i class="fas fa-archive"></i></button>
                    </form>
                </td>
            </tr>
          }
      </tbody>
    </table>
</section>



<!-- Modal Validation suppression séance-->
<div class="modal fade" id="CloneSeance" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">cloner la séance</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Êtes vous sûr de vouloir cloner cette séance?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-primary">Valider</button>
      </div>
    </div>
  </div>
</div>

SensoStat.WebApplication/Views/Session/create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	@model SensoStat.WebApplication.ViewModels.SessionViewModel
}

<div class="p-3">
	<h2>Créer une nouvelle séance</h2>
	<hr />

	<section class="row">
		<!-- div de gestion de la séance -->
		<div class="col-10">
			<form id="formSession" method="post" asp-controller="Session" asp-action="Create">
				<!-- section du nom de la séance ainsi que sont status -->
				<span class="mb-4 d-flex justify-content-between">
					<div class="d-flex">
						<label for="exampleInputEmail1" class="form-label h5 me-1 mt-2">Nom de la séance :</label>
						<span class="">
							<input asp-for="Name" type="text" class="form-control" placeholder="Nom Séance">
						</span>
					</div>
					<div>
						<p class="h5 mt-2">Statut : Non-publié</p>
					</div>
				</span>
				<p>Ajoutez vos instruction(s) / question(s) dans l'ordre chronologique du déroulé de la séance</p>
				<!-- section du message d'accueil -->
				<span class="mb-3 row">
					<div class="col col-lg-2">
						<label>Message d'accueil</label>
					</div>
					<div class="col-10">
						<textarea asp-for="AccueilMsg" class="form-control" rows="1" oninput="auto_grow(this)" placeholder="ici doit être inscrit le message de début de séance !"></textarea>
					</div>
				</span>
				<!-- section qui ajoute des intruction / question -->
				<span id="SpanInstru">
							
				</span>
				<!-- section du message de fin -->
				<span class="mb-3 row">
					<div class="col col-lg-2">
						<label>Message de fin</label>
					</div>
					<div class="col-10">
						<textarea asp-for="FinallMsg" class="form-control" rows="1" oninput="auto_grow(this)" placeholder="ici doit être inscrit le message de fin de séance !"></textarea>
					</div>
				</span>
				<!-- button d'ajout d'instruction / question -->
			</form>
				<button class="btn btn-warning" onclick="addInstruction('Instructions')">Ajouter une instruction</button>
				<button class="btn btn-warning" onclick="addInstruction('Questions')">Ajouter une question</button>
			
		</div>
		<!-- div contenant les button pour les fonctionnalité -->
		<div class="col-2 d-flex flex-column">
			<button class="btn btn-warning mb-2" form="formSession" type="submit">Enregistrer</button>
			<button class="btn btn-warning mb-2" type="button" data-bs-toggle="modal" data-bs-target="#AnnulerSeance">Annuler</button>
		</div>
	</section>
</div>

<!-- Modal Validation suppression séance-->
<div class="modal fade" id="AnnulerSeance" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Annuler la séance</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Êtes vous sûr de vouloir annuler cette séance?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-primary">Valider</button>
      </div>
    </div>
  </div>
</div>

SensoStat.WebApplication/Views/Shared/404.cshtml
<div class="d-flex justify-content-center">
    <pre style="line-height: 1.25; white-space: pre;">
            \          Désolé           /
             \                         /
              \      Cette page       /
               ]    n'existe pas.    [    ,'|
               ]                     [   /  |
               ]___               ___[ ,'   |
               ]  ]\             /[  [ |:   |
               ]  ] \           / [  [ |:   |
               ]  ]  ]         [  [  [ |:   |
               ]  ]  ]__     __[  [  [ |:   |
               ]  ]  ] ]\ _ /[ [  [  [ |:   |
               ]  ]  ] ] (#) [ [  [  [ :===='
               ]  ]  ]_].nHn.[_[  [  [
               ]  ]  ]  HHHHH. [  [  [
               ]  ] /   `HH("N  \ [  [
               ]__]/     HHH  "  \[__[
               ]         NNN         [
               ]         N/"         [
               ]         N H         [
              /          N            \
             /           q,            \
            /                           \
    </pre>
</div>

SensoStat.WebApplication/Views/Shared/EditorTemplates/InstructionItemViewModel.cshtml
@model SensoStat.WebApplication.ViewModels.InstructionItemViewModel

<div class="row">
    <div class="form-group">
        <label asp-for="Libelle" class="control-label"></label>
        <input asp-for="Libelle" class="form-control" /> 
    </div>
</div>

SensoStat.WebApplication/Views/Shared/InstructionItemViewModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model SensoStat.WebApplication.ViewModels.InstructionItemViewModel

<div class="row">
    <div class="form-group">
        <label asp-for="Libelle" class="control-label"></label>
        <input asp-for="Libelle" class="form-control" /> 
    </div>
</div>

SensoStat.WebApplication/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav class="navbar fixed-bottom navbar-light bg-white">
    <div class="container-fluid d-flex justify-content-center">
        <a class="navbar-brand h6 text-wrap fs-6" asp-area="" asp-controller="Home" asp-action="Index" asp-route-pageNumber="1">SensoStat - Tous droits réservés © SensoStat 2022 </a>
    </div>
</nav>

SensoStat.WebApplication/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SensoStat</title>
    <link rel="stylesheet" href="~/css/app.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
    <script src="~/js/app.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css" />
    <script src="~/lib/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
    <script src="~/lib/fontawesome-free-5.15.4-web/js/all.js"></script>
</head>
    <body>
        <!-- Barre de navigation -->
        <!-- Template Bootstrap 5 -->
        @Html.Partial("_NavBar")

        <!-- Conteneur principal -->
        <!-- Template Bootstrap 5 -->
        <div class="container-fluid mb-5 p-4 bg-light h-auto" style="min-height: 960px;">
            @RenderBody()
        </div>

        <!-- Pied de page -->
        <!-- Template Bootstrap 5 -->
        @Html.Partial("_Footer")

        @RenderSection("Scripts", required: false)
    </body>
</html>

<script src="~/js/script.js"></script>

SensoStat.WebApplication/Views/User/Authenticate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model SensoStat.WebApplication.ViewModels.AuthentificationViewModel
}

<div class="p-5">
    <div class="row">
        <form class="col-6 offset-3" method="post" asp-controller="user" asp-action="authenticate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="@Model.Email" class="form-label">Identifiant</label>
                <input asp-for="@Model.Email" name="model.Email" aria-describedby="userAuth" type="text" class="form-control rounded" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Password" class="form-label">Mot de passe</label>
                <input asp-for="@Model.Password" name="model.Password" aria-describedby="userCreate" type="password" class="form-control rounded" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-warning">Se connecter</button>
        </form>
    </div>

</div>

@section Scripts {@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

SensoStat.WebApplication/Views/User/_InstructionItemsViewModel.cshtml
@model SensoStat.WebApplication.ViewModels.SessionViewModel
@Html.EditorFor(m => m.Instructions)